### ISSUE TITLE
npx nx generate not working

### ISSUE THREAD

**Issue by timofeysie** [devinshoemaker/nxtend#83]
Running this command:
```
npx nx generate @nxtend/ionic-react:application ionic-sam
```

Does nothing.  I have the repo [here](https://github.com/timofeysie/quallasuyu/issues) to reproduce this issue.  Not sure if it is an nx CLI issue or not so just trying here first.

**Comment by eranshmil** [comment]
You need to install the dependency `@nrwl/workspace`.

**Comment by devinshoemaker** [comment]
@timofeysie did you install `@nxtend/ionic-react` as a dev dependency? I haven't tested this with` npx` and I imagine that it could cause issues.

**Comment by devinshoemaker** [comment]
@timofeysie did you ever get your issue figured out?

**Comment by timofeysie** [comment]
@devinshoemaker , Doing this seems to work:

```bash
yarn add @nrwl/workspace.
yarn add @nxtend/ionic-react
nx generate @nxtend/ionic-react:application ionic-sam
```

The project gets built.  I saw a node-sass warning, but the new app gets generated:

```bash
warning Error running install script for optional dependency: "C:\\Users\\timof\\repos\\timofeysie\\quallasuyu\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\\Users\\timof\\repos\\timofeysie\\quallasuyu\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass
```

However, the serve fails:

```bash
ng serve ionic-sam
Schema validation failed with the following errors:
  Data path ".builders['build']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['build']" should have required property 'class'.
    at MergeMapSubscriber.project (C:\Users\timof\repos\timofeysie\quallasuyu\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:215:42)
    at MergeMapSubscriber._tryNext (C:\Users\timof\repos\timofeysie\quallasuyu\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
```

My test repo [is here](https://github.com/timofeysie/quallasuyu).

**Comment by timofeysie** [comment]
This also happens with the nx CLI:

```bash
nx serve ionic-sam
> ng run ionic-sam:serve
Schema validation failed with the following errors:
  Data path ".builders['build']" should have required property 'class'.
```

I suppose the serve issue could be separate.  I can close this an open another one if you would like.

**Comment by devinshoemaker** [comment]
Hmm. I worries I’ll dig into it. I haven’t seen anything like that yet but your repo will be helpful. I also haven’t tested this hardly at all on Windows, so I’ll give that a shot as well.

**Comment by timofeysie** [comment]
I wouldn't worry about it.  That repo was build using Nrwl 7 from more than a year ago and I had trouble updating it.  I have [another workspace](https://github.com/timofeysie/clades) created recently which only includes Nrwl 9 projects, and your plugin works fine there.  Using the updated workspace generation and serve succeeds using the following commands:

```bash
yarn add @nxtend/ionic-react
nx generate @nxtend/ionic-react:application luca
nx serve luca
```
